version: '3.8'
services:
  # ── Local Ingress ( simulate ingress on cloud deployments)  ──
  # ── Removing nginx routing/reverse proxy from Frontend pod  ──
  # ── Nginx only serves webpage as a webserver now  ──
  ingress:
    image: nginx:alpine
    container_name: local-ingress
    ports:
      - "80:80"
    volumes:
      - ./local-ingress.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
  frontend:
    build: ./frontend
    ports:
      - "4000:80"
    depends_on:
      - backend
  backend:
    environment:
    - CLUSTER_GCP_URL=https://gcp.nawazishkhan.click
    - CLUSTER_AZURE_URL=https://azure.nawazishkhan.click
    - CLUSTER_AWS_URL=https://aws.nawazishkhan.click
    build: ./backend
    ports:
      - "8080:8080"
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000